package com.example.model

data class LanguageOption(
    val code: String,
    val name: String,
    val nativeName: String,
    val flagEmoji: String
)

object LocalizationManager {

    val SUPPORTED_LANGUAGES = listOf(
        LanguageOption("en", "English", "English", "🇺🇸"),
        LanguageOption("es", "Spanish", "Español", "🇪🇸"),
        LanguageOption("fr", "French", "Français", "🇫🇷"),
        LanguageOption("de", "German", "Deutsch", "🇩🇪"),
        LanguageOption("ja", "Japanese", "日本語", "🇯🇵"),
        LanguageOption("pt", "Portuguese", "Português", "🇧🇷"),
        LanguageOption("it", "Italian", "Italiano", "🇮🇹"),
        LanguageOption("ko", "Korean", "한국어", "🇰🇷"),
        LanguageOption("zh", "Chinese (Simp)", "简体中文", "🇨🇳"),
        LanguageOption("zh-TW", "Chinese (Trad)", "繁體中文", "🇹🇼"),
        LanguageOption("nl", "Dutch", "Nederlands", "🇳🇱"),
        LanguageOption("ru", "Russian", "Русский", "🇷🇺"),
        LanguageOption("hi", "Hindi", "हिन्दी", "🇮🇳"),
        LanguageOption("ar", "Arabic", "العربية", "🇸🇦"),
        LanguageOption("id", "Indonesian", "Bahasa Indonesia", "🇮🇩"),
        LanguageOption("tr", "Turkish", "Türkçe", "🇹🇷"),
        LanguageOption("pl", "Polish", "Polski", "🇵🇱"),
        LanguageOption("sv", "Swedish", "Svenska", "🇸🇪"),
        LanguageOption("no", "Norwegian", "Norsk", "🇳🇴"),
        LanguageOption("da", "Danish", "Dansk", "🇩🇰"),
        LanguageOption("fi", "Finnish", "Suomi", "🇫🇮"),
        LanguageOption("vi", "Vietnamese", "Tiếng Việt", "🇻🇳"),
        LanguageOption("th", "Thai", "ไทย", "🇹🇭"),
        LanguageOption("el", "Greek", "Ελληνικά", "🇬🇷"),
        LanguageOption("cs", "Czech", "Čeština", "🇨🇿"),
        LanguageOption("ro", "Romanian", "Română", "🇷🇴"),
        LanguageOption("hu", "Hungarian", "Magyar", "🇭🇺"),
        LanguageOption("he", "Hebrew", "עברית", "🇮🇱"),
        LanguageOption("ms", "Malay", "Bahasa Melayu", "🇲🇾"),
        LanguageOption("uk", "Ukrainian", "Українська", "🇺🇦"),
        LanguageOption("fil", "Filipino", "Tagalog", "🇵🇭"),
        LanguageOption("sk", "Slovak", "Slovenčina", "🇸🇰"),
        LanguageOption("bg", "Bulgarian", "Български", "🇧🇬"),
        LanguageOption("hr", "Croatian", "Hrvatski", "🇭🇷"),
        LanguageOption("ca", "Catalan", "Català", "🇪🇸"),
        LanguageOption("sr", "Serbian", "Српски", "🇷🇸"),
        LanguageOption("sl", "Slovenian", "Slovenščina", "🇸🇮"),
        LanguageOption("lt", "Lithuanian", "Lietuvių", "🇱🇹"),
        LanguageOption("lv", "Latvian", "Latviešu", "🇱🇻"),
        LanguageOption("et", "Estonian", "Eesti", "🇪🇪"),
        LanguageOption("bn", "Bengali", "বাংলা", "🇧🇩"),
        LanguageOption("ta", "Tamil", "தமிழ்", "🇮🇳"),
        LanguageOption("ur", "Urdu", "اردو", "🇵🇰")
    )

    // Key UI translation dictionary for top languages, with dynamic fallback to English
    private val TRANSLATIONS: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            "tuner_title" to "SHRED SHEETS",
            "subtitle" to "GUITAR TUNER",
            "in_tune" to "PERFECT! IN TUNE! 🤙",
            "tune_up" to "TUNE UP ⬆️ (Too Flat)",
            "tune_down" to "TUNE DOWN ⬇️ (Too Sharp)",
            "listening" to "Pluck a string...",
            "auto_mode" to "AUTO",
            "manual_mode" to "MANUAL",
            "chords" to "Chords",
            "metronome" to "Metronome",
            "anagrams" to "Anagrams",
            "settings" to "Settings",
            "rock_theme" to "Rock ⚡",
            "pop_theme" to "Pop 🎸",
            "get_started" to "LET'S SHRED! 🤙",
            "welcome_title" to "Welcome Future Rockstar! ⚡",
            "welcome_desc" to "Tune with the Shaka fist, explore beginner chords, master rhythm, and create crazy string anagrams!",
            "select_instrument" to "Select Your Instrument",
            "choose_vibe" to "Choose Your Music Style",
            "sound_on" to "Sounds Enabled",
            "dark_mode" to "Dark Mode",
            "light_mode" to "Light Mode",
            "play_sound" to "Hear Tone 🔊",
            "strum_chord" to "Strum Chord 🎸",
            "tap_tempo" to "TAP TEMPO",
            "custom_anagram" to "Create Custom Anagram",
            "save_anagram" to "Save Rockstar Anagram"
        ),
        "es" to mapOf(
            "tuner_title" to "SHRED SHEETS",
            "subtitle" to "AFINADOR DE GUITARRA",
            "in_tune" to "¡PERFECTO! AFINADO! 🤙",
            "tune_up" to "SUBIR ⬆️ (Muy Grave)",
            "tune_down" to "BAJAR ⬇️ (Muy Agudo)",
            "listening" to "Toca una cuerda...",
            "auto_mode" to "AUTO",
            "manual_mode" to "MANUAL",
            "chords" to "Acordes",
            "metronome" to "Metrónomo",
            "anagrams" to "Anagramas",
            "settings" to "Ajustes",
            "rock_theme" to "Rock ⚡",
            "pop_theme" to "Pop 🎸",
            "get_started" to "¡A TOCAR! 🤙",
            "welcome_title" to "¡Bienvenido Futuro Rockstar! ⚡",
            "welcome_desc" to "¡Afina con el puño Shaka, descubre acordes y crea divertidos anagramas!",
            "select_instrument" to "Selecciona tu Instrumento",
            "choose_vibe" to "Elige tu Estilo",
            "sound_on" to "Sonidos Activados",
            "dark_mode" to "Modo Oscuro",
            "light_mode" to "Modo Claro",
            "play_sound" to "Escuchar Tono 🔊",
            "strum_chord" to "Rasguear Acorde 🎸",
            "tap_tempo" to "PULSO RÍTMICO",
            "custom_anagram" to "Crear Anagrama",
            "save_anagram" to "Guardar Anagrama"
        ),
        "fr" to mapOf(
            "tuner_title" to "SHRED SHEETS",
            "subtitle" to "ACCORDEUR GUITARE",
            "in_tune" to "PARFAIT! ACCORDÉ! 🤙",
            "tune_up" to "MONTER ⬆️ (Trop Bas)",
            "tune_down" to "DESCENDRE ⬇️ (Trop Haut)",
            "listening" to "Pincez une corde...",
            "auto_mode" to "AUTO",
            "manual_mode" to "MANUEL",
            "chords" to "Accords",
            "metronome" to "Métronome",
            "anagrams" to "Anagrammes",
            "settings" to "Réglages",
            "get_started" to "C'EST PARTI! 🤙",
            "welcome_title" to "Bienvenue Futur Rockstar! ⚡"
        ),
        "de" to mapOf(
            "tuner_title" to "SHRED SHEETS",
            "subtitle" to "GITARREN-STIMMGERÄT",
            "in_tune" to "PERFEKT! GESTIMMT! 🤙",
            "tune_up" to "HÖHER ⬆️ (Zu tief)",
            "tune_down" to "TIEFER ⬇️ (Zu hoch)",
            "listening" to "Saite zupfen...",
            "auto_mode" to "AUTO",
            "manual_mode" to "MANUELL",
            "chords" to "Akkorde",
            "metronome" to "Metronom",
            "anagrams" to "Eselsbrücken",
            "settings" to "Einstellungen",
            "get_started" to "LOS GEHT'S! 🤙",
            "welcome_title" to "Willkommen Zukünftiger Rockstar! ⚡"
        ),
        "ja" to mapOf(
            "tuner_title" to "SHRED SHEETS",
            "subtitle" to "ギターチューナー",
            "in_tune" to "完璧！チューニング完了！🤙",
            "tune_up" to "上げる ⬆️ (低すぎ)",
            "tune_down" to "下げる ⬇️ (高すぎ)",
            "listening" to "弦を弾いてください...",
            "auto_mode" to "自動",
            "manual_mode" to "手動",
            "chords" to "コード",
            "metronome" to "メトロノーム",
            "anagrams" to "覚え歌",
            "settings" to "設定",
            "get_started" to "スタート！🤙",
            "welcome_title" to "未来のロックスターへ！⚡"
        ),
        "pt" to mapOf(
            "tuner_title" to "SHRED SHEETS",
            "subtitle" to "AFINADOR DE GUITARRA",
            "in_tune" to "PERFEITO! AFINADO! 🤙",
            "tune_up" to "SUBIR ⬆️ (Muito Grave)",
            "tune_down" to "DESCER ⬇️ (Muito Agudo)",
            "listening" to "Toque uma corda...",
            "auto_mode" to "AUTO",
            "manual_mode" to "MANUAL",
            "chords" to "Acordes",
            "metronome" to "Metrônomo",
            "anagrams" to "Mnemônicos",
            "settings" to "Configurações",
            "get_started" to "VAMOS TOCAR! 🤙",
            "welcome_title" to "Bem-vindo Futuro Rockstar! ⚡"
        )
    )

    fun getString(key: String, languageCode: String = "en"): String {
        return TRANSLATIONS[languageCode]?.get(key)
            ?: TRANSLATIONS["en"]?.get(key)
            ?: key
    }
}
